export const types = {

    SET_MODAL_VISIBILITY : 'SET_MODAL_VISIBILITY',
    SET_PRIVACY_VISIBLITY : 'SET_PRIVACY_VISIBLITY',
    SET_CONFIRM_VISIBLITY : 'SET_CONFIRM_VISIBLITY',
    SET_VERIFICATION_VISIBLITY : 'SET_VERIFICATION_VISIBLITY',
    SET_RESET_PASSWORD_VISIBILITY: 'SET_RESET_PASSWORD_VISIBILITY',
    SET_TWITTER_BUTTON_ACTIVE : 'SET_TWITTER_BUTTON_ACTIVE',
    SET_TWITTER_REPLAY_VISIBILITY: 'SET_TWITTER_REPLAY_VISIBILITY',
    SET_REPLAY_CONTENT: 'SET_REPLAY_CONTENT',
    SET_POST_DETAILS: 'SET_POST_DETAILS',
    SET_TWEET_MODAL_VISIBILITY: 'SET_TWEET_MODAL_VISIBILITY',
    SET_FONT_WEIGHT_SEEN: 'SET_FONT_WEIGHT_SEEN',
    SET_EDIT_MODAL_VISIBLE: 'SET_EDIT_MODAL_VISIBLE'
    
}