export const types = {

    SET_MODAL_VISIBILITY : 'SET_MODAL_VISIBILITY',
    SET_PRIVACY_VISIBLITY : 'SET_PRIVACY_VISIBLITY',
    SET_CONFIRM_VISIBLITY : 'SET_CONFIRM_VISIBLITY',
    SET_VERIFICATION_VISIBLITY : 'SET_VERIFICATION_VISIBLITY',
    SET_RESET_PASSWORD_VISIBILITY: 'SET_RESET_PASSWORD_VISIBILITY',
    SET_TWITTER_BUTTON_ACTIVE : 'SET_TWITTER_BUTTON_ACTIVE'

}